'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('vs', {
  kind: 'workspace',
  getWorkspace: (id) => ipcRenderer.invoke('ws:get', id),
  loadState: (id) => ipcRenderer.invoke('state:load', id),
  saveState: (id, state) => ipcRenderer.invoke('state:save', id, state),

  fsList: (dir) => ipcRenderer.invoke('fs:list', dir),
  fsFileIndex: (repoPath) => ipcRenderer.invoke('fs:fileIndex', repoPath),
  gitStatus: (repoPath) => ipcRenderer.invoke('git:status', repoPath),
  fsRead: (file) => ipcRenderer.invoke('fs:read', file),
  fsWrite: (file, content) => ipcRenderer.invoke('fs:write', file, content),
  fsCopyInto: (opts) => ipcRenderer.invoke('fs:copyInto', opts),
  fsCreate: (dirPath, fileName) => ipcRenderer.invoke('fs:create', { dirPath, fileName }),
  fsMkdir: (dirPath, name) => ipcRenderer.invoke('fs:mkdir', { dirPath, name }),
  fsRename: (from, to) => ipcRenderer.invoke('fs:rename', { from, to }),
  fsDelete: (p) => ipcRenderer.invoke('fs:delete', { path: p }),
  gitDiff: (repoPath, opts) => ipcRenderer.invoke('git:diff', repoPath, opts),
  gitLog: (opts) => ipcRenderer.invoke('git:log', opts),
  gitCommit: (sha) => ipcRenderer.invoke('git:commit', sha),
  gitCommitFileDiff: (sha, file) => ipcRenderer.invoke('git:commitFileDiff', sha, file),
  gitBranch: () => ipcRenderer.invoke('git:branch'),
  dropPath: (file) => { try { return webUtils.getPathForFile(file); } catch { return null; } },
  reveal: (file) => ipcRenderer.invoke('fs:reveal', file),
  openFolder: (dir) => ipcRenderer.invoke('fs:openFolder', dir),

  ptyCreate: (opts) => ipcRenderer.invoke('pty:create', opts),
  ptyList: () => ipcRenderer.invoke('pty:list'),
  ptyWrite: (termId, data) => ipcRenderer.send('pty:write', termId, data),
  lagReport: (r) => ipcRenderer.send('diag:lag', r),
  ptyResize: (termId, cols, rows) => ipcRenderer.send('pty:resize', termId, cols, rows),
  ptyKill: (termId) => ipcRenderer.send('pty:kill', termId),
  claudeStarted: (wsId, termId, opts) => ipcRenderer.send('pty:claudeStarted', wsId, termId, opts),
  sessionPinned: (wsId, termId, sessionId) => ipcRenderer.send('pty:sessionPinned', wsId, termId, sessionId),
  sessionCheck: (wsId, sessionId, cwd) => ipcRenderer.invoke('sessions:check', wsId, sessionId, cwd),
  sessionLastReply: (wsId, sessionId, cwd) => ipcRenderer.invoke('sessions:lastReply', wsId, sessionId, cwd),
  sessionTabName: (wsId, sessionId, cwd, taken) => ipcRenderer.invoke('sessions:tabName', wsId, sessionId, cwd, taken),
  // worktree tabs (main/worktrees.cjs); main derives the repo from the window
  wtCreate: (wsId, name) => ipcRenderer.invoke('wt:create', wsId, name),
  wtList: (wsId) => ipcRenderer.invoke('wt:list', wsId),
  wtRemove: (wsId, name, opts) => ipcRenderer.invoke('wt:remove', wsId, name, opts),
  feedSnapshot: (wsId) => ipcRenderer.invoke('feed:snapshot', wsId),
  boardOthers: (wsId) => ipcRenderer.invoke('board:others', wsId),
  boardWatch: (on) => ipcRenderer.send('board:watch', Boolean(on)),
  boardFocus: (wsId) => ipcRenderer.invoke('board:focus', wsId),
  bgList: () => ipcRenderer.invoke('bg:list'),
  onBoardChanged: (cb) => ipcRenderer.on('board:changed', () => cb()),
  presenceGet: () => ipcRenderer.invoke('presence:get'),
  presenceSet: (mode) => ipcRenderer.invoke('presence:set', mode),
  onPresence: (cb) => ipcRenderer.on('presence:changed', (e, p) => cb(p)),
  // claude accounts (main/accounts.cjs): State = { accounts: [...], pick }
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: (label, token) => ipcRenderer.invoke('accounts:add', label, token),
  accountsRemove: (id) => ipcRenderer.invoke('accounts:remove', id),
  accountsRename: (id, label) => ipcRenderer.invoke('accounts:rename', id, label),
  accountsMove: (id, delta) => ipcRenderer.invoke('accounts:move', id, delta),
  accountsSwitchAll: (id) => ipcRenderer.invoke('accounts:switchAll', id),
  accountsClear: (id) => ipcRenderer.invoke('accounts:clear', id),
  onAccountsChanged: (cb) => ipcRenderer.on('accounts:changed', (e, state) => cb(state)),
  setTermAccount: (termId, accountId) => ipcRenderer.invoke('accounts:setTerm', termId, accountId),
  waitClaudeExit: (termId, timeoutMs, noKill) => ipcRenderer.invoke('pty:waitClaudeExit', termId, timeoutMs, Boolean(noKill)),
  claudeRunning: (termId) => ipcRenderer.invoke('pty:claudeRunning', termId),
  onAccountSwitch: (cb) => ipcRenderer.on('account:switch', (e, msg) => cb(msg)),

  appRestart: () => ipcRenderer.invoke('app:restart'),
  ptyBusy: (wsId) => ipcRenderer.invoke('pty:busy', wsId),
  claudeVersion: () => ipcRenderer.invoke('util:claudeVersion'),
  openLogs: () => ipcRenderer.invoke('util:openLogs'),
  notifyGet: () => ipcRenderer.invoke('notify:get'),
  notifySet: (patch) => ipcRenderer.invoke('notify:set', patch),
  pickLogo: () => ipcRenderer.invoke('dialog:pickLogo'),
  logoCandidates: () => ipcRenderer.invoke('logo:candidates'),
  updateLogo: (id, logoPath) => ipcRenderer.invoke('ws:updateLogo', id, logoPath),
  writeClipboard: (text) => ipcRenderer.invoke('util:writeClipboard', text),
  readClipboard: () => ipcRenderer.invoke('util:readClipboard'),
  copyDiagnostics: (wsId) => ipcRenderer.invoke('util:copyDiagnostics', wsId),

  onPtyData: (cb) => ipcRenderer.on('pty:data', (e, termId, chunk) => cb(termId, chunk)),
  onPtyExit: (cb) => ipcRenderer.on('pty:exit', (e, termId) => cb(termId)),
  onSessionFound: (cb) => ipcRenderer.on('session:found', (e, termId, sessionId) => cb(termId, sessionId)),
  onTermStatus: (cb) => ipcRenderer.on('term:status', (e, termId, st) => cb(termId, st)),
  onTermFocus: (cb) => ipcRenderer.on('term:focus', (e, termId) => cb(termId)),
  onTermFeed: (cb) => ipcRenderer.on('term:feed', (e, msg) => cb(msg && msg.termId, msg && msg.feed)),
  onAccountLimits: (cb) => ipcRenderer.on('account:limits', (e, limits) => cb(limits)),
  onTreeChanged: (cb) => ipcRenderer.on('tree:changed', () => cb()),
  onUpdaterState: (cb) => ipcRenderer.on('updater:state', (e, state) => cb(state)),
  onAppUpdateAvailable: (cb) => ipcRenderer.on('app:updateAvailable', (e, info) => cb(info)),
});
